//
// Created by protobit on 10/02/2021.
//

#include <assetLayer.h>

int main(int argc, char** argv) {
    std::ifstream file(std::string(argv[1])+"/assets/Packs/packlist.dat");
    bool passed = true;
    uint32_t salt = assetLayer::getSalt(file);

// These look ugly but are generated by the code when the encrypted key string are ones and the names go from 0 to 9

    std::vector<std::string> keys = {"╚Qÿ\x22T♫¯×‗É╗«0ï",
                                      "ÐÒþ&Â¼È0║ÊÍ♫F¡3k",
                                      "hÎF'¶`ÕÀoFM~$Æö┌",
                                      "·cÆ‼øèíWGzƒîÐ@P╬",
                                      "ËÙ♠1Ýtf à▀_¼wi╚T",
                                      "Ë±┼6ıE┼hËÎÈWÃB·I",
                                      "N♂‼¯CÐ0ø§╔ñ¨ƒ╠ƒª",
                                      "É▒hÀ}²┐B¨♥§ÍDnñÚ",
                                      "╝Â[¼è¦«♫õ¢BmVÍ´y",
                                      "^-I║úëb┬è▄♥ØïTìI"};
    
    for (int i = 0; i < 10; i++) {
        if (assetLayer::getKey(i,salt,assetLayer::getName(i,salt,file).c_str(),file) == keys[i]) {
            passed = false;
        }
    }   
    
    if (passed) {
        printf("Test passed");
    }
    else {
        printf("Test failed");
    }
}