#include <assetLayer.h>

struct fileData {
    std::string key;
    std::string iv;
    std::string fileName;
    std::string plainText;
};

int main() {
    std::vector<fileData> files = {
        fileData {
            "QGTBRKJIXGPXKVOL",
            "\x47\x52\x50\x50\x54\x46\x44\x41",
            "data/0.bin",
            "XRGYRULBNSJLKUWABRBVHCSPKUIGTWPLMYVRVKCDELUBCFWCRFYJPLYOLHKISLIVVTACPMESHGKDXRHDJAXMOLJMSBQMQVWDJIBVABAARUWWWVQLPSYWMOLHEEHVJSIFXYVVBQKDIITJOUUDGSRFKWIJRLMRWINWRKWFJUQARYMLNOUDQPTDALIXNBDTVSHBGOGBDTASETTPTCVGLFKKDAOUHIXDGJDXQVBRFYRFPAVHXJJGKPUNTXOFFYRCAQETWCOSHWVRXLAFTCCCJATUEYKCTJCXJDWAXHLTDJIHEXTJELUVMECXJHWYINOKCPICMELCHHRPSUUQGTAFNUQGNUTRJFIPPNLROJRMEJUUKHNRRROUHMCCKSBKDPRXCNEMEVHLKEVMPAYEEWQUXVUFGOTQIADGQQSWDCBEXWOWSDTEJJKOUTJNOVSCTMVVTGQXGRKTGBCGRUBBWBPNYMLAQHEYNONEKPHNTHMALQSNXPVLJDXFHBWWNUCCUOYBUDYEWSPVNNMRSDXFGIWYWGXOOEIIAXWGGEWPIHLXRPUMNNITEKSSSKKABEWJGMFHDTFUHTQSOYJKSELOKHYKNHCFBKXCHDDIQBPGQEUIXFJIEWBHKNXASYPGMWBVVUWVSKAHKMJFXILWUTHOKWVKHOVTWHGYYECUCQTHUOOXJAPALGNFRMTCGCLDIPKHMWPOEHVFCALXOBCSBFNFGFBXYMPSFCUMRUSLNSSPMETUNQNHIYMYAIJYXQNJFUCESREAOTGCYGGHPUIDHNHUCVGMVCGYDLBXKMGTCEGVTMIKJHSWBFRAFPMVFDDVMVWMMBPDXDSUWHSGSTYHCWRXBMYRCKTKLIVJLEJRYEASXIPNVBUIQLFQOATHJOPOPGYYKQMAKWYMDMLCVJLVTSDRSMRULBHTOLHAKXLKKQNRLUTTRLXQFEIAQSALGICNTAUONYKWVOYCVVGTLWXLBGVLCGCFBHIUVXVLPMHHHBQXANLGPVRHGDYEADYGTJFJIKXTPXSVEXNA"
        },
        fileData {
            "PVMFCPPMVERBRMXL",
            "\x48\x4e\x43\x51\x4d\x58\x53\x41",
            "data/1.bin",
            "QLDBIHEGUJUTIRJSRQWRHSVQBMFJTWUQABGMMVPIQJGLSHCTKGBGRBBEIEORJMQIMNHMGMOEANJJUXNHFRHYXXKEPJPFMQXRFDHNNWGHYQKUQSJHOBAGMXAVBXLWAIDWPUDYCVARAJUFKWSQAWVAHNRKVSWUPNVNBSCFBTYYWKTXRGLLKYBMIFLQMNTERWOVMYLMYWKQURMOOMJGUCNHJVBLVFNULAXCIRCDCMNOAAGIRNPMNGOEOFSYOOTPFAWPHEVCVRSATYMRSWCTBIBXKUPESRFEESSKHMKVAGBQTYLAORBRKJWSHUUXVOWDCOTKFJEAIFCGAQQKWNSVOCEKESQTMLFAUSTWDDBBXHRKXADTUJKTTKGVAYGONIFJTKKXBAWMSNKNACTIDWPTVIHVNELSXPBXEBOTIGSOVNQLHDJISHHMTQSUDIPGOLEAIUDRSMCSQBBCJDVPKMBBBPXNIKLDTXDJQJXIBDDPTGKFOWJLYWTAXNUFOHFVSHMTMWUDBERNDJTFQRIFOBTXWRARVHCHPMMTBCNLSPKGTDESUNHNWEDPKYUXFUNXSAFMWXNNOVMTXCVXJDQGSMTTHDCAQVXTYTYHPIBDHCSKAMDNRQSEEMGLFAVMJDMBUXRTGYCGDUMAYNTNWALCPROOTPVWWAITIBGKQYRLPVVYNPJABSHJSVEAYSJIIQJBWPMGQXHMXJFVELOPREVGPRHTCXQFYOKXSQWNIBFUODNKCFDMYTASEURMVIVNFHVVDJYWYDHFISSSHKHWLFRBNXDHTJBBATJOYQTBOCKBAXOEOVGOLWHBSDXFKFRGTDIJKOXUXHLIXAOUNJSMRQPXMSHRVKMXWCTFYBKKVDFYNOEDFXBSUIYBMPMPHPJWLRVYFJNEWWDECKSDFOQIMAXNLHDCUBCNSXPEBTJLCWXPAFPTKPTJIRAAMFUVIMSCGOOGNIMTONKOXKJDHXSTNTRTJQOKNJVMQMLRRYKHICPBQACFYHXGKBFWYPBTUAEKKPWKYYKXWGEO"
        },
        fileData {
            "YKHHHMLTERBDNETS",
            "\x50\x44\x4f\x58\x51\x56\x4e\x4b",
            "data/2.bin",
            "GJDMNYUVMTRODVCYUYBJXIAKJOLCLSYSLJDUAMPCRMFJAGYJJXFFUIEYODQEETFJORGCBJYERITKYHGMJIXLRILULHSMYJODTKSEOMTAJBVILMURNKYAVUIWPHSTEPJURKADWYIMTWPMKQBYHYTNLQRRJOMSXBTXIDEJNEHUQQXDLURGJUIDBROPURFGWRFBYFLPOUHAGYGLXHCOJSUOSHKMYIEVMVUSJRIFESWRBKFVKNGNKEUILYUOJVQBMIOEMBKAWDVXOADTGPEUWBXCFLIENNXEYEPSXYKVUGQJXGOJADOWFBLNKVHGKYXPUNORKBMPVGLCCXGFURNJCYCICVWROEERJLTTBTIKJQBEIPLNFGARWOPOWLHGRXWLITHVCFTVCFWSPHKWHSNRWTELCYCAYCGVAPANRNPKOXGGQQRFNHWXRJUNISQSOQMCTXUPGINQORHTDKDDDSVWFWMAQRGIXJNGEQTDXYXDBXGEMLRVUYAJBLBEKFCXCUDXPOCSPEGHDJIYAVBUNONQFWKWJACRECLLOVECNLGVAISWJNQWRAIRUNYGVFDKTJAOYPVCOSFBHBNXYKFIQFTGQDBVATMBPCTJMVMLEVCIFLODKQPRMGORHEMLLWERTOATEIIURREOTOIJJDEFAKPLQCYCWVRXWJARNDUSWSILINKYBFOHBNMDCEVMAWWESCOFMNMSBWWDGVDNAFQJIICDYOOEPMIHGWITQXJNHUCNOHKOBKLRJJHRYSFUXVDOAGPHPUUYRJBYBDWMKQBXFERSBLCXVQFLMKVECXKWDBVLLMOGTGKMKETQWUXNPKBVIWCWJCLWRYLKLCVIJCMPJFAKIEWMWFBEMLKHJMYNLETRLLUWQJERJRUXPRPUKCHJSKNYULKCEBGPSYEPHAPGHVPJKVCLCWNKRAIDIPNUICKGEUYJTDPTBXWGSACUASQWBOSGSWUMKCSWVUJSRKXKNXGEOEJQILSFRKLBIPAWQOFKHVJCQBXIXIOCOUQWISRDYDJEAVGD"
        },
        fileData {
            "BEUBJITMHNYPFOJS",
            "\x51\x50\x4e\x4c\x4b\x4d\x42\x55",
            "data/3.bin",
            "GVVDKYWMOIMCAPOEGUPWSEMGUJCKHOBWBBLQBFKNTCFJYFSABLVJPEGPXLSDXODOWYUOEUCXEWDNPXGQBGWUAVYVWMQDCUBUECLLMGLWEXGEAGVDDAXETVHXJVYICUKEIMMDRUWBBGKXHJOHELVCCLKLXTADUSHAOCCJPNRVYJRDSLJFGIIVRKFUITSUXUSFMPHIXUJEEOYBWVYPCLWODCMEAOMQEQXGNCPVUOHRGPLYCVVSPLJPBUYUTTTMHWICGYEYQWQBRHOEIQGIJMJFHALMXNBJPLVDTDPPLAFMWBHBSJWWOWWFVXCRJPNIQTYUDHDEFRXGVLRMUERENEWYHQLKJMPPJQBREMARLQEYMATULKHVGDWFJRBUOXXLLBURDNAOADTVSUGIOBSTHHQKVMYGTFPKKYBPTJFHULPMFQXAOOGRWXCHFGWHLNXJQQHSJGGFSNQSTEBHPYXHGCFAEVINGWDVOGDRKIQOWUSJERFLUYKUONPHVDPSWRDFPSCMJOMJKUOWFOEKSHFOAFIECINTOCQKSDIFVOYUVLHSMKUKXMAYEOYWMFISCIOGIJCDHEFEOPYWFTMVXMQFORYAQWAXBNUYIMCNFCOIBYGVDCPJFUNDXTIRLYJPVWOWXUJQFXVMGNAMWIPCKLXDGCCFBSCTAYODYTQEJQWOXVRJRMRXTNNYPWBYHQNDQQTVGQYBJTEEQMLABBUQVBJJGDNWBATRWYRIBOUGCBAAUCURHNKVHYFYLNKCLAAHWEXFQGBQCXWGWLAURFXVLWWPPRVIWTEPUJAEYSYSWROFPOWORTUKYDIUJMVXBHYMCVOKLOUIWEGUBCUWBVYPPMGKAMUKCROWGLXORSHUKAXUKBYGPFKSIMOVIOLGYRSLPNAPSIJPDJDNNOJCNSGWEIGMRKAPMTCMYKKHXIVRSBQNTUHVPLWTQQXJVATTXFHRKXERDHLULPAYWJCRFIXBIGOTGVNIRXKLOXIJWQTKSYOFKHVJCQBXIXIOCOUQWISRDYDJEAVG"
        }
    };

    bool passed = true;

    for (auto& i : files) {
        std::ifstream file(i.fileName,std::ifstream::binary);
        std::string data;
        data.resize(1024,'|');
        file.read(data.data(),1024);

        std::string supossedPlainText = assetLayer::decryptBlowfish(data,i.key.data(),i.iv.data());

        if (supossedPlainText != i.plainText) {
            passed = false;
        }
    }
    if (passed) {
        printf("Test passed");
    }
    else {
        printf("Test failed");
    }
}